---
- hosts: "{{ host_env | default('web') }}"
  remote_user: "{{ root_user | default('root') }}"
  become: yes
  vars:
    _user: "{{ username | default('artslob') }}"
  tasks:
    - include_vars: secrets.yml

    - name: add default user with name "{{ _user }}"
      user:
        name: "{{ _user }}"
        password: "{{ vault_password | password_hash('sha512', vault_salt) }}"
        comment: Master of the Universe
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
