---
- hosts: "{{ host_env | default('web') }}"
  remote_user: "{{ root_user | default('root') }}"
  become: yes
  vars:
    _user: "{{ username | default('artslob') }}"
  tasks:
    - include_vars: secrets.yml

    - name: add default user with name "{{ _user }}"
      user:
        name: "{{ _user }}"
        password: "{{ vault_user_password | password_hash('sha512', vault_user_salt) }}"
        comment: Master of the Universe
        shell: /bin/bash
        groups: sudo
        append: yes
        create_home: yes
        state: present
        generate_ssh_key: no
    #    generate_ssh_key: yes
    #    ssh_key_bits: 4096

    - name: add authorized key for user "{{ _user }}" copying it from local user
      authorized_key:
        user: "{{ _user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    - name: copy private and public keys to vps
      copy:
        src: "vps-ssh-keys/{{ item.name }}"
        dest: "/home/{{ _user }}/.ssh/{{ item.name }}"
        mode: "{{ item.mode }}"
        owner: "{{ _user }}"
        group: "{{ _user }}"
        backup: yes
      with_items:
        - { name: 'id_rsa',     mode: '0400' }
        - { name: 'id_rsa.pub', mode: '0444' }

    - name: enable passwordless sudo for user "{{ _user }}"
      copy:
        content: '{{ _user }} ALL=(ALL) NOPASSWD:ALL'
        dest: "/etc/sudoers.d/90-{{ _user }}"
        owner: root
        group: root
        mode: 0440
