---
- hosts: "{{ host_env | default('web') }}"
  vars:
    username: "{{ root_user | default('artslob') }}"
    homedir: "/home/{{ username }}"
    dotfiles_dir: "{{ homedir }}/.dotfiles"
  remote_user: "{{ username }}"
  become: no
  tasks:
    - name: Clone dotfile repository
      git:
        dest: "{{ dotfiles_dir }}"
        repo: git@github.com:artslob/dotfiles.git
        accept_hostkey: yes

    - name: Use stow to create symbolic links
      command: stow -t "{{ homedir }}" --adopt {{ item }}
      args:
        chdir: "{{ dotfiles_dir }}"
      with_items:
        - bash
        - git
        - vim

    - name: Set platform for bash
      copy:
        content: vps
        dest: '{{ homedir }}/.bash-config/platform'