---
- hosts: "{{ host_env | default('web') }}"
  vars:
    username: "{{ root_user | default('artslob') }}"
  remote_user: "{{ username }}"
  become: yes
  tasks:
    - name: Set timezone to Europe/Moscow
      timezone:
        name: Europe/Moscow
