---
- hosts: ec2
  become: yes
  remote_user: artslob

  tasks:
    - include_role: name=hostname
    - include_role: name=sshd-config
    - include_role: name=packages
    - import_role: name=dotfiles
      become: no
    - include_role: name=iptables
