---
- hosts: ec2
  become: yes
  remote_user: ubuntu

  tasks:
    - include_vars: secrets.yml

    - include_role:
        name: 'create-user'

- hosts: ec2
  become: yes
  remote_user: artslob

  tasks:
    - include_role: name=hostname
    - include_role: name=sshd-config
    - include_role: name=packages
    - import_role: name=dotfiles
      become: no
    - include_role: name=iptables
    - include_role: name=ssl
    - include_role: name=nginx
    - include_role: name=timezone
    - include_role: name=mt-proxy
