---
- name: Update cache and install packages
  apt:
    package: "{{ packages }}"
    update_cache: yes

#- name: Disable systemd-resolved caching DNS daemon
#  systemd:
#    service: systemd-resolved
#    state: stopped
#    enabled: no
